### ISSUE TITLE
Wrong variable?

### ISSUE THREAD

**Issue by BeeHiveJava** [redpois0n/oslib#1]
I noticed at line 195 in the OperatingSystem class, you refer to longName: https://github.com/redpois0n/oslib/blob/master/src/com/redpois0n/oslib/OperatingSystem.java#L195

Is this correct? Or should this be "uname", defined at line 190: https://github.com/redpois0n/oslib/blob/master/src/com/redpois0n/oslib/OperatingSystem.java#L190

Cheers,

U2 For Me

**Comment by wille** [comment]
That is correct. Thank you for pointing it out.
